use_frameworks!

platform :ios, '10.0'

target 'BinarySwiftCode_Example' do
  pod 'BinarySwiftCode', :path => '../'

  target 'BinarySwiftCode_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
